name: Create and publish a Docker image of the static website

# Run this action on push to the main branch and manually from the UI.
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64

# Allow access to everything that's needed.
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

# Do not allow multiple deployments.
concurrency:
  group: 'push'
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Telegram that the workflow was triggered
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *Building [${{ github.repository }}](https://github.com/${{ github.repository }})*
            
            Action was triggered by a commit from [${{ github.actor }}](https://github.com/${{ github.actor }}):
            `${{ github.event.commits[0].message }}`
            
            See changes: [${{github.sha}}](https://github.com/${{ github.repository }}/commit/${{github.sha}})
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
        id: checkout
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx for multi-platform build
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Build and publish Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.PLATFORMS }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Get Docker image download URL
        uses: actions/github-script@v7
        id: image-sha
        with:
          script: return "${{ steps.push.outputs.imageid }}".substring(7)
          result-encoding: string
      - name: Notify on Telegram that the workflow finished
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *Docker Image Published [${{ github.repository }}](https://github.com/${{ github.repository }})*
            
            Updated website Docker image was built and published to [ghcr.io/${{ github.repository }}:sha256-${{ steps.image-sha.outputs.result }}](https://ghcr.io/${{ github.repository }}:sha256-${{ steps.image-sha.outputs.result }})
      - name: Generate build artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
